version: '3'

services:
  couchpotato:
    image: linuxserver/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - ./couchpotato/config:/config
      - ./deluge/autoadd:/downloads
      - ./couchpotato/movies:/movies
    environment:
      - PGID=$GID
      - PUID=$UID
    depends_on:
      - deluge
      - jackett

  deluge:
    image: linuxserver/deluge
    ports:
      - "58846:58846"
      - "8112:8112"
    volumes:
      - ./deluge/downloads:/downloads
      - ./deluge/config:/config
      - ./deluge/autoadd:/autoadd
    environment:
      - PGID=$GID
      - PUID=$UID

  jackett:
    image: linuxserver/jackett
    ports:
      - "9117:9117"
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    environment:
      - PGID=$GID
      - PUID=$UID

  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - "32400:32400"
    environment:
      - PLEX_UID=$UID
      - PLEX_GID=$GID
    network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./deluge/downloads/done:/data
